error: add new DownloadError
(cherry picked from commit 2c551f6d549cb63965d81c3dc6125d185031c9d5)

Change-Id: I5454ac109096fd479d8e379485665b4dd4e1df41